### ISSUE TITLE
Only run 1 validator at a time (from left to run)

### ISSUE THREAD

**Issue by dcworldwide** [mikeerickson/validatorjs#139]
## Problem

With rules like so:

```
code: 'required|min:3|unique_code',
```

where **unique_code** is a async validator, the unique_code logic will be run on each keystroke, even if min:3 throws an error.
## Proposed solution

As unique_code is expensive (as most async calls are), I think that we should change the rules engine, so that there is an option to only validate 1 rule at a time. So in this case, if min:3 fails, subsequent rules will be skipped.

**Comment by garygreen** [comment]
Although not well documented, there is [`stopOnError`](https://github.com/skaterdav85/validatorjs/blob/master/src/validator.js#L373). I think it's what your looking for. In laravel there's similar functionality but it's added to the rules (called `"bail"`)

**Comment by mogarick** [comment]
@dcworldwide I hope you have solved your problem. 
Even though it's been almost 6 month since you posted this I think the current behavior is OK and what you may need to do is to make sure your property changes only after a blur event or applying some debounce like logic in order to avoid to run the validation on every keystroke.
