### ISSUE TITLE
set default value

### ISSUE THREAD

**Issue by sapolang** [mikeerickson/validatorjs#250]
set default value

**Comment by vict-shevchenko** [comment]
@sapolang can you please properly describe your issue? provide some code snippet? Maintainers do not read one's thoughts.

**Comment by mikeerickson** [comment]
@sapolang We will surely consider adding a feature, but as @vict-shevchenko  stated we need more (much more in fact) information as to what it is you are looking for.  The very vague subject doesnt give us much to go on.

**Comment by Spring3** [comment]
I don't exactly know what the author had in his mind, but I also faced the situation, when I need to have a default value set for some of the props that I validate.

I imagine it to myself like this:
```js
// model
{
  limit: 'numeric|fallback:10',
  offset: 'numeric|fallback:0',
  sorting: 'string|in:asc,desc|fallback:asc',
  filter: 'string|fallback:all',
  createdAt: `date|fallback:${new Date().toUTCString()}`
}
```

From the implementation perspective, because there might be some additional rules following the possible `fallback` rule (like for example `digit:length` or `in:` etc ), the `fallback` rule must be processed prior to those. Ideally, after the type is identified (`string`, `email`, `numeric`, `date` etc), because this info is enough to know how to convert the fallback value into the expected format.

So, in case of a string/number in the example above, the chain of processing would be:
__limit__: `numeric (type identified) -> fallback (check if given, apply if not)`.
__sorting__: `string -> fallback (set value as 'asc' if not given) -> in:asc,desc`

If in the second case, there was something like the following (and the value was not set):
```js
{
  sorting: 'string|in:asc,desc|fallback:foo'
}
```
it must result with a validation error, due to the invalid `in` rule condition (`foo` is not among the `asc,desc`)

__What if required is given?__
```js
{
  email:  'email|required|fallback:test@mail'
}
```
My opinion is that it should not result with an error and just apply the fallback before checking for `required`. Actually, such combination of required with fallback is redundant and required rule can be safely skipped.

__What if a value comes in?__
In case the value is given, `fallback` rule can be skipped. If both `fallback` and `required` rules are given and the value is provided, then both of them can be skipped during the validation logic

The name of the rule can also be changed to `default` or any other, if you think one is more accurate. Or you can have aliases if you support ones

I hope this made it a bit more clear. Again, I don't know what the author expected, but this is just my vision of such feature

**Comment by garygreen** [comment]
Default values should really live in userland. What if you want to get the data back WITH the default values?   Given your examples you should probably look into `present` rule
