### ISSUE TITLE
Add Alpha_Dash that only allows Alpha and Dash/Underscore, but prevents Numbers

### ISSUE THREAD

**Issue by GeorgeWL** [mikeerickson/validatorjs#348]
Proposed Solution:
`alpha`
`alpha_num`
`alpha_dash`
`alpha_num_dash`
 as properties as opposed to `alpha-dash` covering both alpha numeric and dash/underscore.

single-responsibility.

**Comment by vict-shevchenko** [comment]
I think the best solution for you will be to create your custom rule.

**Comment by GeorgeWL** [comment]
I think that `alpha_dash` implies to me `alpha` ruleset and dash/underscore.  

Not `alpha_num` ruleset and dash/underscore.

**Comment by mikeerickson** [comment]
@GeorgeWL I am going to see about adding this as built-in for the 3.19 release

**Comment by mikeerickson** [comment]
@GeorgeWL After reviewing this closer, we are going to leave it as-is.  Making changes as you have proposed will have negative breaking changes for those who have used the current rules.  I may consider adding something like `alpha_dash_only`

Otherwise, use the recommendation from @vict-shevchenko and create a custom rule

**Comment by GeorgeWL** [comment]
I really like the idea of adding a new rule for it actually.
