### ISSUE TITLE
Numeric based validation rules issue

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#47]
At the moment the validator does a [basic type-check](https://github.com/skaterdav85/validatorjs/blob/master/src/validator.js#L171) to see if it should compare the length or actual value.

For example, this should validate that the person is a min of 18 years old, but because it's a string of 20 it's validated against it's character length, even though the 'integer' rule is there. 

``` javascript
var v = new Validator({ age: '20' }, { age: 'required|integer|min:18' });
if (v.fails())
{
    console.log('error', v.errors); // The age must be at least 18 characters.
}
```

Laravel [handles this](https://github.com/illuminate/validation/blob/master/Validator.php#L938) by a `getSize` method and checking if there is numeric-based rules, if so compares it as such, if not then compares it's length. This is how it also supports arrays etc.

**Comment by fairbairn** [comment]
I have a similar issue as such...

~~~
var Validator = require('validatorjs');

var v = new Validator({ amount: '123000.45' }, { amount: 'required|numeric|min:4|max:9' });
if (v.fails())
{
    console.log('error', v.errors); 
    
    // error { errors: { amount: [ 'The amount must be less than 9 characters.' ] } }

}

~~~

I can't tell when min, max is checking length or the actual numeric value.

In our cases, we're using web forms so it's always a string... we think it's trying to check value which is fine, we can set it like this instead...

~~~
var Validator = require('validatorjs');

var v = new Validator({ amount: '123000.45' }, { amount: 'required|numeric|min:1000|max:99999' });
if (v.fails())
{
    console.log('error', v.errors);

    // error { errors: { amount: [ 'The amount must be less than 99999 characters.' ] } }
}

~~~

but it's default error message makes no sense because it still thinks it's failing on "characters" instead of a value out of range.

I think the BUG is that when the type is numeric and min and max are value ranges, the error message is incorrect.
