### ISSUE TITLE
[Idea] Success messages

### ISSUE THREAD

**Issue by garygreen** [mikeerickson/validatorjs#64]
It could be quite useful to have 'success messages' where you want to display feedback to the user about each rule (or maybe just one overall success message).

For instance, if your building a form that outputs a list of errors for a field, you could also (as you start typing) check in real time which rules are passing:
- Username is more than 5 characters ✓
- Username is not taken ✓

Ideally don't want to overcomplicate validatorjs but I think there is some value in this feature.

**Comment by iamdtang** [comment]
I don't think Laravel's validator does this right? For the real time scenario, couldn't you just check passes() and if true, display a corresponding success message? I think adding success messages might bloat the library too much since you'd have to include translations and allow for customizing success messages on a one off basis, just like with error messages. What do you think of having this as an "addon" - basically a separate script that gets included after validatorjs?
